# Generated by Django 3.0.14 on 2021-08-07 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20210720_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_content_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_content_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_content_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_title_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_title_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_title_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url_6',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
