# Generated by Django 3.0.14 on 2021-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20210807_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_1',
            field=models.ImageField(null=True, upload_to='post_image'),
        ),
    ]
