# Generated by Django 3.0.14 on 2021-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20210811_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
